from pathlib import Path
path = Path('scripts/youtube_to_knowledge.py')
text = path.read_text()
old = """def analysis_with_openai(clean_text: str, metadata: dict) -> dict:\n    if not OPENAI_API_KEY:\n        return {}\n    openai_client = openai.OpenAI(api_key=OPENAI_API_KEY)\n    chunk = clean_text[:8000]\n    prompt = (\n        \"Du är en strukturerad research-assistent. Utifrån följande transcript \"\n        \"ska du ge svar i följande JSON-objekt. \\n\" \n        \"Fields:\\n\"\n        \"core_topic, core_idea, features (lista), tools (lista), workflows (lista), guides (lista), \"\n        \"strategic_insights (lista), monetization (lista), automation_opportunities (lista), relevance_to_me, \"\n        \"skill_candidate {{should_create(bool), reason, skill_description, draft_outline}}, classification(list), related_concepts(list)\\n\"\n        f\"Transcript:\\n{chunk}\"\n    )\n    response = openai_client.chat.completions.create(\n        model=\"gpt-4o-mini\",\n        messages=[\n            {\"role\": \"system\", \"content\": \"Du genererar strukturerad JSON\"},\n            {\"role\": \"user\", \"content\": prompt},\n        ],\n        temperature=0.3,\n    )\n    text = response.choices[0].message.content\n    try:\n        data = json.loads(text.strip())\n    except json.JSONDecodeError:\n        data = {}\n    return data\n"""
new = """def analysis_with_openai(clean_text: str, metadata: dict) -> dict:\n    if not OPENAI_API_KEY:\n        return {}\n    openai_client = openai.OpenAI(api_key=OPENAI_API_KEY)\n    chunk = clean_text[:8000]\n    prompt = (\n        \"You are a structured knowledge distillation engine. Given the transcript below, return valid JSON with the fields:\\n\"\n        \"core_topic, core_idea, features (array), tools (array), workflows (array), guides (array), strategic_insights (array), \\n\"\n        \"monetization (array), automation_opportunities (array), relevance_to_me, related_concepts (array), classification (array), skill_candidate (object with should_create (bool), reason, skill_description, draft_outline).\\n\"\n        \"Transcript:\\n\" + chunk\n    )\n    response = openai_client.chat.completions.create(\n        model=\"gpt-4o-mini\",\n        messages=[\n            {\"role\": \"system\", \"content\": \"You produce JSON output only.\"},\n            {\"role\": \"user\", \"content\": prompt},\n        ],\n        temperature=0.3,\n    )\n    text = response.choices[0].message.content\n    try:\n        data = json.loads(text.strip())\n    except json.JSONDecodeError:\n        data = {}\n    return data\n\n\ndef ensure_analysis(analysis: dict, info: dict) -> dict:\n    default = {\n        \"core_topic\": info.get(\"title\", \"Unknown topic\"),\n        \"core_idea\": info.get(\"description\", \"\"),\n        \"features\": [],\n        \"tools\": [],\n        \"workflows\": [],\n        \"guides\": [],\n        \"strategic_insights\": [],\n        \"monetization\": [],\n        \"automation_opportunities\": [],\n        \"relevance_to_me\": \"Säger något om varför detta relaterar till dina projekt.\",\n        \"related_concepts\": [],\n        \"classification\": [],\n        \"skill_candidate\": {\"should_create\": False},\n    }\n    default.update({k: v for k, v in analysis.items() if v})\n    return default\n"""
if old not in text:
    raise SystemExit('old block not found')
text = text.replace(old, new)
path.write_text(text)
"""
path.write_text(open('scripts/_modify_analysis.py').read())
PY