from pathlib import Path
path = Path('scripts/youtube_to_knowledge.py')
text = path.read_text()
old = 'def ensure_analysis(analysis: dict, info: dict) -> dict:\n    base = {\n        "core_topic": info.get("title", "Unknown topic"),\n        "core_idea": info.get("description", ""),\n        "features": [],\n        "tools": [],\n        "workflows": [],\n        "guides": [],\n        "strategic_insights": [],\n        "monetization": [],\n        "automation_opportunities": [],\n        "relevance_to_me": "Säger något om varför detta relaterar till dina projekt.",\n        "related_concepts": [],\n        "classification": [],\n        "skill_candidate": {"should_create": False},\n    }\n    base.update({k: v for k, v in analysis.items() if v})\n    return base'
new = 'def ensure_analysis(analysis: dict, info: dict, clean_text: str) -> dict:\n    base = {\n        "core_topic": info.get("title", "Unknown topic"),\n        "core_idea": info.get("description", ""),\n        "features": [],\n        "tools": [],\n        "workflows": [],\n        "guides": [],\n        "strategic_insights": [],\n        "monetization": [],\n        "automation_opportunities": [],\n        "relevance_to_me": "Säger något om varför detta relaterar till dina projekt.",\n        "related_concepts": [],\n        "classification": [],\n        "skill_candidate": {"should_create": False},\n    }\n    base.update({k: v for k, v in analysis.items() if v})\n    if not analysis:\n        base['features'] = heuristic_extract(clean_text, HEURISTIC_KEYWORDS['features'])\n        base['tools'] = heuristic_extract(clean_text, HEURISTIC_KEYWORDS['tools'])\n        base['workflows'] = heuristic_extract(clean_text, HEURISTIC_KEYWORDS['workflows'])\n        base['guides'] = heuristic_extract(clean_text, HEURISTIC_KEYWORDS['guides'])\n        base['strategic_insights'] = heuristic_extract(clean_text, HEURISTIC_KEYWORDS['strategic_insights'])\n        base['classification'] = simple_classifications(clean_text)\n    if not base['classification']:\n        base['classification'] = simple_classifications(clean_text)\n    if not base.get('skill_candidate'):\n        base['skill_candidate'] = {"should_create": False}\n    return base'
if old not in text:
    raise SystemExit('block not found')
path.write_text(text.replace(old, new, 1))
print('ensure_analysis updated')
